
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

dist: jammy

language: python

python:
  - "3.10"

cache: pip

# command to install dependencies
install:
  - pip install setuptools==65.6.3
  - pip install Deprecated~=1.2.13
  - pip install html-testRunner~=1.2.1
  # - pip install -r requirements.txt

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
